version: '3'

services:
  postgres:
    image: postgres:10.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testapi-example
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  postgres-data: